### ISSUE TITLE
Fix Typo

### ISSUE THREAD

**Issue by giorgiofellipe** [viniciusdacal/viniciusdacal.github.com#1]
http://www.viniciusdacal.com/pt/iniciante/2015/02/09/como-deixar-o-terminal-do-mac-colorido.html
Nesse post há um pequeno equívoco no subtítulo "Abilitando as cores", o correto seria "Habilitando as cores".

Muito bacana seu blog, parabéns! ;)

**Comment by viniciusdacal** [comment]
Passou batido.
Muito obrigado pela correção.
Abraços :)

**Comment by viniciusdacal** [comment]
pull request #2
